name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout master"
      uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
    - run: |
        shellcheck *.sh
